### ISSUE TITLE
Topic shouldn't be null terminated

### ISSUE THREAD

**Issue by tobyjaffey** [feabhas/MQTT-c-pub-sub#1]
At https://github.com/feabhas/MQTT-c-pub-sub/blob/master/src/mqtt.c#L286 you zero terminate the topic string. This isn't correct.
If I run this code against the mosquitto broker, the extra '\0' is interpreted as the first byte of the payload. As mosquitto returns C strings, this makes the payload appear to be empty.

http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#publish

**Comment by nscooling** [comment]
Hi Toby, thanks I'll take a look and fix this. Niall.
